function Hd_taps = fir_rcos(Interp_factor, N_slow_samples_one_side, rolloff)
%FIR_RCOS_15 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 02-Oct-2015 12:09:15

SPS        = Interp_factor;                  % Samples per Symbol
PulseShape = 'Raised Cosine';                % Pulse shape
N          = 2*N_slow_samples_one_side*SPS;  % Filter Order
Beta       = rolloff;                        % Rolloff Factor

h = fdesign.pulseshaping(SPS, PulseShape, 'n,beta', N, Beta);

Hd = design(h, 'window');

Hd_taps = Hd.Numerator;


